base_url = "https://virto.network"
title = "Virto Network"
description = "Developer platform for building Web3 applications with VirtoSDK and the Kreivo blockchain."
default_language = "en"
compile_sass = false
build_search_index = false
[languages.es]
title = "Virto Network"
description = "Plataforma para desarrolladores que construyen aplicaciones Web3 con VirtoSDK y la blockchain Kreivo."

[extra]
calendly = "https://calendly.com/virtonetwork"
apply_url = "https://forms.gle/pgFVmfbu4zv6qdMs8"

[[extra.nav]]
link_en = "About Us"
link_es = "Sobre Nosotros"
route = "/about"
class = "menu-item"

[[extra.nav]]
link_en = "Kreivo"
link_es = "Kreivo"
route = "/kreivo"
class = "menu-item"

[[extra.nav]]
link_en = "Get Started"
link_es = "Empezar"
route = "/docs"
class = "app-button-link button"

[[extra.footer]]
link_en = "About Us"
link_es = "Sobre Nosotros"
route = "/about"

[[extra.footer]]
link_en = "Kreivo"
link_es = "Kreivo"
route = "/kreivo"

[[extra.footer]]
link_en = "Whitepaper"
link_es = "Whitepaper"
route = "/docs/whitepaper/"

[extra.globals]
go_up_en = "Back to Top"
go_up_es = "Volver arriba"
go_down_en = "Scroll to Bottom"
go_down_es = "Ir al final"
