base_url = "https://virto.network"
title = "Virto Network"
description = "Your multi-currency wallet for managing group funds and making quick decisions through a voting system."
default_language = "en"
compile_sass = false
build_search_index = false
generate_feeds = true
feed_filenames = ["rss.xml"]

[languages.es]
title = "Virto Network"
description = "Tu billetera multimoneda para gestionar fondos en grupo y tomar decisiones rápidas mediante un sistema de votación."
generate_feeds = true
feed_filenames = ["rss.xml"]

[extra]
calendly = "https://calendly.com/virtonetwork"
apply_url = "https://forms.gle/pgFVmfbu4zv6qdMs8"

[[extra.nav]]
link_en = "About Us"
link_es = "Sobre Nosotros"
route = "/about"
class = "menu-item"

[[extra.nav]]
link_en = "Services"
link_es = "Servicios"
route = "/services"
class = "menu-item"

[[extra.nav]]
link_en = "Use Cases"
link_es = "Casos de Uso"
route = "/cases"
class = "menu-item"

[[extra.nav]]
link_en = "Blog"
link_es = "Blog"
route = "/blog"
class = "menu-item"

[[extra.nav]]
link_en = "Explore virto-connect"
link_es = "Explorar virto-connect"
route = "https://demo.virto.dev/"
class = "app-button-link button"

[[extra.footer]]
link_en = "About Us"
link_es = "Sobre Nosotros"
route = "/about"

[[extra.footer]]
link_en = "Services"
link_es = "Servicios"
route = "/services"

[[extra.footer]]
link_en = "Use Cases"
link_es = "Casos de Uso"
route = "/cases"

[[extra.footer]]
link_en = "Blog"
link_es = "Blog"
route = "/blog"

[[extra.footer]]
link_en = "Whitepaper"
link_es = "Whitepaper"
route = "/docs/whitepaper/"

[extra.globals]
go_up_en = "Back to Top"
go_up_es = "Volver arriba"
go_down_en = "Scroll to Bottom"
go_down_es = "Ir al final"
