name: Site

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.19.2

      - name: Build site
        run: zola build
        env:
          AIRTABLE_API_KEY: ${{ vars.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ vars.AIRTABLE_BASE_ID }}
          AIRTABLE_TABLE_ID: ${{ vars.AIRTABLE_TABLE_ID }}
